---
title: "Kustkarnor"
author: "Richard J. Telford"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
theme_set(theme_bw())
```

```{r load-data}
loadd(fos_percent)
```

```{r stratigraphies, results = "hide"}
mgp <- c(1.5, .3, 0)
par(tcl = -0.2, mgp = mgp)

fos_data <- fos_percent %>% 
  pivot_longer(cols = -(site:date), names_to = "taxon", values_to = "percent") %>% 
  group_by(site, taxon) %>% 
  filter(
    max(percent) >= 3, 
    sum(percent > 0) >= 3 
  ) %>% 
  group_by(site) %>% 
  nest() %>% 
  mutate(
    data = map(data, ~pivot_wider(.x, names_from = "taxon", values_from = "percent")), 
    data = map(data, ~arrange(.x, date))
    )

map2(
  .x = fos_data$data, 
  .y = fos_data$site,
  ~ strat.plot(
    d = select(.x, -(sample:date)) %>% as.data.frame(),
    yvar = pull(.x, date),
    xLeft = 0.1,
    yBottom = .09,
    yTop = 0.7,
    xRight = 0.98,
    scale.percent = TRUE,
    title = .y, 
    ylabel = "Year CE",
    mgp = mgp
  ))
  
```

## Coverage plots

```{r coverage}
readd(coverage_plots)
```

## Analogue quality

```{r analogue}
readd(ana_qual)
```

## Residual length

```{r reslen}
readd(reslen_plot)
```

## Transfer function

Performance

```{r performance}
readd(mod_wa) %>% 
  performance() %>% 
  pluck("crossval") %>% 
  knitr::kable()
```

Reconstructions

```{r recon-plot}
readd(pred_plot)
```

## Reconstruction significance

```{r recon_sig}
cowplot::plot_grid(plotlist = readd(recon_sig)$recon_sig_plot)
```

